# Generated by Django 5.1.1 on 2025-01-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ofclass', models.CharField(max_length=100, null=True)),
                ('division', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('discription', models.CharField(max_length=100, null=True)),
                ('video', models.FileField(null=True, upload_to='Video/')),
                ('thumbnail', models.FileField(null=True, upload_to='Thumbnail/')),
                ('academic_year', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('domain', models.CharField(max_length=100, null=True)),
                ('Achievements', models.CharField(max_length=100, null=True)),
                ('LevelofProject', models.CharField(max_length=100, null=True)),
                ('Challenges', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
